services:


  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: backend-kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: backend-zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://backend-kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    networks:
      - web-scraping-micro-network


  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: backend-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - web-scraping-micro-network


  mysql:
    container_name: backend-mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - web-scraping-micro-network


  discovery-service:
    build: ./discovery-service
    container_name: backend-discovery-service
    ports:
      - "8761:8761"
    networks:
      - web-scraping-micro-network

  api-gateway-service:
    build: ./api-gateway-service
    env_file:
      - ./api-gateway-service/.env
    container_name: backend-api-gateway-service
    ports:
      - "8080:8080"
    networks:
      - web-scraping-micro-network
    depends_on:
      - discovery-service


  article-service:
    build: ./article-service
    env_file:
      - ./article-service/.env
    container_name: backend-article-service
    ports:
      - "8083:8083"
    networks:
      - web-scraping-micro-network
    depends_on:
      - discovery-service
      - kafka
      - mysql


  auth-service:
    build: ./auth-service
    env_file:
      - ./auth-service/.env
    container_name: backend-auth-service
    ports:
      - "8081:8081"
    networks:
      - web-scraping-micro-network
    depends_on:
      - discovery-service
      - mysql


  scrap-service:
    build: ./scrap-service
    env_file:
      - ./scrap-service/.env
    container_name: backend-scrap-service
    ports:
      - "8082:8082"
    networks:
      - web-scraping-micro-network
    depends_on:
      - kafka
      - discovery-service



volumes:
  mysql_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  web-scraping-micro-network:
    driver: bridge