spring:
  application:
    name: article-service

  datasource:
    url: ${ARTICLE_DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 60000


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


  kafka:
    consumer:
      group-id: article-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "com.example.articleservice.dto.ArticleDto"
        spring.json.use.type.headers: false
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}

server:
  port: 8083
